import { schema } from 'spacetimedb/server';

export {
  CatalogRiceVariety,
  CatalogYeastProduct,
  CatalogKojiSporeProduct,
  AcidType,
  MineralSalt,
  MineralSaltIon,
  InventoryRiceLot,
  InventoryYeastStock,
  InventoryKojiSporeLot,
} from './catalog';

export {
  User,
  UserIdentity,
  Entity,
  Recipe,
  Process,
  WaterProfile,
  ProcessParamSpec,
  ProcessStageSpec,
  ProcessMaterialSlotSpec,
  ProcessStepSpec,
  ProcessStepFieldSpec,
  RecipeProcessUse,
  RecipeMaterialSpec,
  RecipeProcessMaterialBinding,
  WaterProfileIon,
  TaskSpec,
} from './recipe';

export {
  Batch,
  BatchProcessInstance,
  BatchStageInstance,
  BatchStepInstance,
  BatchStepFieldValue,
  BatchMaterialPlan,
  BatchTaskInstance,
} from './batch';

import {
  CatalogRiceVariety,
  CatalogYeastProduct,
  CatalogKojiSporeProduct,
  AcidType,
  MineralSalt,
  MineralSaltIon,
  InventoryRiceLot,
  InventoryYeastStock,
  InventoryKojiSporeLot,
} from './catalog';

import {
  User,
  UserIdentity,
  Entity,
  Recipe,
  Process,
  WaterProfile,
  ProcessParamSpec,
  ProcessStageSpec,
  ProcessMaterialSlotSpec,
  ProcessStepSpec,
  ProcessStepFieldSpec,
  RecipeProcessUse,
  RecipeMaterialSpec,
  RecipeProcessMaterialBinding,
  WaterProfileIon,
  TaskSpec,
} from './recipe';

import {
  Batch,
  BatchProcessInstance,
  BatchStageInstance,
  BatchStepInstance,
  BatchStepFieldValue,
  BatchMaterialPlan,
  BatchTaskInstance,
} from './batch';

export default schema({
  User,
  UserIdentity,
  Entity,
  Recipe,
  Process,
  WaterProfile,
  ProcessParamSpec,
  ProcessStageSpec,
  ProcessMaterialSlotSpec,
  ProcessStepSpec,
  ProcessStepFieldSpec,
  RecipeProcessUse,
  RecipeMaterialSpec,
  RecipeProcessMaterialBinding,
  WaterProfileIon,
  TaskSpec,
  CatalogRiceVariety,
  CatalogYeastProduct,
  CatalogKojiSporeProduct,
  AcidType,
  MineralSalt,
  MineralSaltIon,
  InventoryRiceLot,
  InventoryYeastStock,
  InventoryKojiSporeLot,
  Batch,
  BatchProcessInstance,
  BatchStageInstance,
  BatchStepInstance,
  BatchStepFieldValue,
  BatchMaterialPlan,
  BatchTaskInstance,
});
